name: Tests
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
